### ISSUE TITLE
read_weight_history parsing failure

### ISSUE THREAD

**Issue by dugite-code** [dugite-code/miscale.py#5]
```
Traceback (most recent call last):
  File "./miscale2.py", line 275, in <module>
    main(sys.argv[1:])
  File "./miscale2.py", line 262, in main
    records = read_weight_history( mac_address )
  File "./miscale2.py", line 149, in read_weight_history
    data = format_weight( data )
  File "./miscale2.py", line 108, in format_weight
    byte0 = bin(int(data[i][0].decode("hex"), 16))[2:].zfill(8)
ValueError: invalid literal for int() with base 16: '\x03'
```

This is a failure to catch extra responses that the weight que doesn't issue

Example scale output:
```
Characteristic value was written successfully
/..Useful data./
Notification handle = 0x0022 value: 03
```

**Comment by dugite-code** [comment]
Further reteach sows I am interpreting the binary data incorrectly.

`bin(int(data[i][0].decode("hex"), 16))` is not the correct way to read  the first byte
